### ISSUE TITLE
Incorrect Answer

### ISSUE THREAD

**Issue by phukeo** [JonnyBloor/Benandjonny#1]
What about including a message to the user if they guess wrong?

**Comment by JonnyBloor** [comment]
Yes this is possible, but I'm wondering do you get an 'end of line error' in the terminal when you run it?

**Comment by phukeo** [comment]
I've got an answer to this issue, but can't upload atm as I don't have permission :/

**Comment by phukeo** [comment]
Have uploaded a pull request which deals with this issue.

**Comment by phukeo** [comment]
#2 - Closed with pull request
